@startuml
 (*) --> "Home Fragment "
  -->"我要提款点击"
  -->"财务结算"
  "财务结算" -->[点击常见问题] "常见问题html"
  "财务结算" -->[点击查看异常订单] "异常订单详情"
  "财务结算" --> [点击结算详情行]"结算详情"
  "结算详情" --> [点击分类 如一分钱洗车] "订单列表"
  "订单列表" --> [过滤条件选择] "显示具体过滤后订单列表"
@enduml